import type { DogProfile, FosterParent, ScheduledTask, Volunteer } from "@/types";

export const volunteers: Volunteer[] = [
  {
    id: "v1",
    role: "volunteer",
    name: "Jordan Lee",
    location: { neighborhood: "Mission", city: "San Francisco", state: "CA" },
    phone: "(415) 555-0142",
    email: "jordan.lee@example.com",
    bio: "Weekday mornings are my dog-walking time. Happy to help with vet runs too if I can drive.",
    skills: ["dog-walking", "vet-transport"],
    availability: ["Mon AM", "Wed AM", "Fri AM"],
    availabilityExceptions: [],
    maxTravelMiles: 5,
    hasVehicle: true,
    reliability: { tasksClaimed: 18, tasksCompleted: 17, lateReleases: 1, memberSince: "2025-11-03" },
  },
  {
    id: "v2",
    role: "volunteer",
    name: "Priya Nair",
    location: { neighborhood: "Sunset", city: "San Francisco", state: "CA" },
    phone: "(415) 555-0198",
    email: "priya.nair@example.com",
    bio: "I foster-sat during vet school and love overnight stays with anxious dogs.",
    skills: ["overnight-sitting", "training"],
    availability: ["Weekends"],
    availabilityExceptions: [],
    maxTravelMiles: 10,
    hasVehicle: false,
    reliability: { tasksClaimed: 9, tasksCompleted: 9, lateReleases: 0, memberSince: "2026-02-14" },
  },
  {
    id: "v3",
    role: "volunteer",
    name: "Marcus Chen",
    location: { neighborhood: "SoMa", city: "San Francisco", state: "CA" },
    phone: "(415) 555-0173",
    email: "marcus.chen@example.com",
    bio: "Can grab supplies on my lunch break most days, and I take good adoption photos.",
    skills: ["supply-runs", "photography"],
    availability: ["Tue PM", "Thu PM"],
    availabilityExceptions: [],
    maxTravelMiles: 8,
    hasVehicle: true,
    reliability: { tasksClaimed: 22, tasksCompleted: 19, lateReleases: 2, memberSince: "2025-08-30" },
  },
];

export const fosterParents: FosterParent[] = [
  {
    id: "f1",
    role: "foster",
    name: "Alex Rivera",
    location: { neighborhood: "Bernal Heights", city: "San Francisco", state: "CA" },
    phone: "(415) 555-0110",
    email: "alex.rivera@example.com",
    bio: "Fostering for three years, usually one dog at a time in a fenced yard.",
    activeDogIds: ["d1"],
    yearsFostering: 3,
    householdNotes: "No other pets. Fenced backyard. Quiet street.",
    matchingProfile: {
      housingType: "house",
      yard: "fenced",
      activityLevel: "active",
      hoursAwayPerDay: 4,
      residentPets: [],
      experience: ["Large dogs", "Leash reactivity", "Daily medication"],
      preferences: ["One dog at a time", "Adult dogs", "Active companionship"],
    },
  },
  {
    id: "f2",
    role: "foster",
    name: "Sam Okafor",
    location: { neighborhood: "Richmond", city: "San Francisco", state: "CA" },
    phone: "(415) 555-0187",
    email: "sam.okafor@example.com",
    bio: "New foster parent, appreciate extra help with walks while I learn the ropes.",
    activeDogIds: ["d2"],
    yearsFostering: 0,
    householdNotes: "One resident cat, cat-experienced dogs preferred.",
    matchingProfile: {
      housingType: "apartment",
      yard: "none",
      activityLevel: "moderate",
      hoursAwayPerDay: 7,
      residentPets: ["Cat"],
      experience: ["First-time foster"],
      preferences: ["Small or medium dogs", "Cat-friendly", "Lower energy"],
    },
  },
];

export const dogs: DogProfile[] = [
  {
    id: "d1",
    name: "Biscuit",
    photoUrl: "/biscuit-profile.svg",
    fosterParentId: "f1",
    breed: "Lab mix",
    age: 4,
    size: "large",
    energyLevel: "high",
    status: "needs-vet",
    temperament: ["friendly", "food-motivated", "leash-reactive"],
    goodWith: { kids: true, dogs: false, cats: false },
    feeding: {
      foodBrand: "Purina Pro Plan",
      timesPerDay: 2,
      amountPerMeal: "1.5 cups",
      allergies: ["chicken"],
    },
    medical: [
      {
        condition: "Mild hip dysplasia",
        medication: "Glucosamine chews",
        instructions: "Give one chew with dinner daily.",
      },
    ],
    quirks: ["Afraid of skateboards", "Loves belly rubs", "Counter-surfs if food is left out"],
    behaviorObservations: [
      {
        id: "bo1",
        category: "trigger",
        behavior: "Pulls away when skateboards pass",
        context: "Morning walk on a busy block. Recovered after we crossed the street and gave him space.",
        observedAt: "2026-08-22T08:15:00",
        concernLevel: "watch",
        sharedWithShelter: true,
      },
      {
        id: "bo2",
        category: "progress",
        behavior: "Settled calmly after breakfast",
        context: "Chose his bed without prompting and rested for about 40 minutes.",
        observedAt: "2026-08-21T09:00:00",
        concernLevel: "routine",
        sharedWithShelter: false,
      },
      {
        id: "bo3",
        category: "progress",
        behavior: "Settled quietly during a delivery",
        context: "Stayed relaxed on his mat while I signed for a package. No barking at all.",
        observedAt: "2026-08-20T17:30:00",
        concernLevel: "routine",
        sharedWithShelter: true,
        authorRole: "volunteer",
        authorName: "Jordan Lee",
      },
      {
        id: "bo4",
        category: "routine",
        behavior: "Relaxed on his mat while I cooked",
        context: "Stayed calm and settled for the whole evening instead of counter-surfing.",
        observedAt: "2026-08-19T19:00:00",
        concernLevel: "routine",
        sharedWithShelter: true,
        authorRole: "foster",
        authorName: "Alex Rivera",
      },
      {
        id: "bo5",
        category: "routine",
        behavior: "Left most of his dinner",
        context: "Didn't eat more than a few bites. Second night in a row that he has walked away.",
        observedAt: "2026-08-22T19:30:00",
        concernLevel: "watch",
        sharedWithShelter: true,
        authorRole: "foster",
        authorName: "Alex Rivera",
      },
      {
        id: "bo6",
        category: "routine",
        behavior: "Refused breakfast",
        context: "No appetite this morning. He sniffed the bowl and walked away from it.",
        observedAt: "2026-08-22T07:45:00",
        concernLevel: "watch",
        sharedWithShelter: true,
        authorRole: "foster",
        authorName: "Alex Rivera",
      },
    ],
    intakeDate: "2026-05-12",
  },
  {
    id: "d2",
    name: "Nutmeg",
    fosterParentId: "f2",
    breed: "Chihuahua mix",
    age: 2,
    size: "small",
    energyLevel: "moderate",
    status: "available-for-adoption",
    temperament: ["shy at first", "affectionate once warmed up"],
    goodWith: { kids: false, dogs: true, cats: true },
    feeding: {
      foodBrand: "Hill's Science Diet",
      timesPerDay: 3,
      amountPerMeal: "1/3 cup",
      allergies: [],
    },
    medical: [],
    quirks: ["Hides during thunderstorms", "Needs a slow, quiet introduction"],
    behaviorObservations: [
      {
        id: "bo7",
        category: "progress",
        behavior: "Played with a rope toy for ten minutes",
        context: "Brought it back twice. First time I have seen her start a game on her own.",
        observedAt: "2026-08-21T18:00:00",
        concernLevel: "routine",
        sharedWithShelter: true,
        authorRole: "foster",
        authorName: "Sam Okafor",
      },
      {
        id: "bo8",
        category: "progress",
        behavior: "Zoomies in the hallway after dinner",
        context: "Played until she flopped over, then came for a cuddle. Happy and relaxed.",
        observedAt: "2026-08-22T20:15:00",
        concernLevel: "routine",
        sharedWithShelter: true,
        authorRole: "foster",
        authorName: "Sam Okafor",
      },
    ],
    intakeDate: "2026-07-30",
  },
];

export const scheduledTasks: ScheduledTask[] = [
  {
    id: "t1",
    dogId: "d1",
    type: "vet-visit",
    scheduledFor: "2026-08-23T10:00:00",
    status: "assigned",
    assignedVolunteerId: "v1",
    notes: "Hip dysplasia follow-up. Bring current glucosamine chew schedule.",
  },
  {
    id: "t2",
    dogId: "d1",
    type: "medication",
    scheduledFor: "2026-08-22T20:00:00",
    status: "open",
    notes: "Evening glucosamine chew with dinner.",
  },
  {
    id: "t3",
    dogId: "d2",
    type: "dog-walking",
    scheduledFor: "2026-08-24T09:00:00",
    status: "open",
    notes: "Needs a slow, quiet handler — shy around new people.",
  },
];
